### ISSUE TITLE
Optional parameter as async or vm_list does not reach the IM service in some cases

### ISSUE THREAD

**Issue by micafer** [indigo-dc/im-java-api#52]

**Comment by micafer** [comment]
Reported by Marica.
/cc @maricaantonacci

**Comment by alpegon** [comment]
Fixed in PR #53

**Comment by maricaantonacci** [comment]
Hi @alpegon and @micafer 
I've just made a test with the fixed version of the library and the problem is solved as far as I can see.

Thank you very much!
