### ISSUE TITLE
Allow to specify timeouts for requests

### ISSUE THREAD

**Issue by alberto-brigandi** [indigo-dc/im-java-api#54]
Hi,
right now both the connection timeout (`ClientProperties.CONNECT_TIMEOUT`) and the read timeout (`ClientProperties.READ_TIMEOUT`) are set to the default value (which corresponds to infinite)

It'd be nice to able to specify a custom value at client creation time

**Comment by micafer** [comment]
New functions has been added to the InfrastructureManager class:

```java
  /**
   * Set the client connection timeout in milliseconds.
   *
   * @param connectTimeout
   *          : int with the client connection timeout
   */
  public void setConnectTimeout(final int connectTimeout)
 

  /**
   * Set the client read timeout in milliseconds.
   *
   * @param readTimeout
   *          : int with the client read timeout
   */
  public void setReadTimeout(final int readTimeout) 
```
